### ISSUE TITLE
Plugin is crashed when did not set $ANDROID_HOME environment value

### ISSUE THREAD

**Issue by ganadist** [dbgsprw/AndroidPropertyManager#1]
Here is crash stacktrace log.

null
java.lang.NullPointerException
    at view.PluginViewFactory.SelectedDeviceChanged(PluginViewFactory.java:102)
    at view.PluginViewFactory.viewComponentInit(PluginViewFactory.java:171)
    at view.PluginViewFactory.createToolWindowContent(PluginViewFactory.java:92)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:521)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$12.run(ToolWindowManagerImpl.java:559)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ganadist** [comment]
SDK location can read from $IDEA_CONFIG_DIR/options/project.default.xml , and element name is "android.sdk.path".

**Comment by ganadist** [comment]
You can see in this code how get sdk path.

https://android.googlesource.com/platform/tools/adt/idea/+/studio-master-dev/android/src/com/android/tools/idea/sdk/IdeSdks.java#61

**Comment by dbgsprw** [comment]
I added source that find Android home path of Android SDK.
Thank you for your help.

**Comment by ganadist** [comment]
If you enter bug number in commit message, github will close bug automatically.
Please see https://help.github.com/articles/closing-issues-via-commit-messages/
